version: '3.7'
services:
  database:
    image: mysql:5.7
    container_name: bookstoredb
    environment:
      MYSQL_ROOT_PASSWORD: R1234r
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - booknet
  bookstore:
    build: .
    container_name: bookstoreapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - booknet
networks:
    booknet:
        driver: bridge